### ISSUE TITLE
Missing Intercom/Intercom.h

### ISSUE THREAD

**Issue by ifero** [tinycreative/react-native-intercom#150]
Hello everyone,
I am facing this very strange and OLD problem that was affecting RN ≤ 0.40 users.
I have a brand new Xcode project in swift (4.0) using cocoa pods (1.3.1).
I have added, as you say, all the requirements in the podfile but I always have problems with the imports.

in **IntercomUserAttributesBuilder.m**
```
#import <Intercom/Intercom.h>   //file not found
```

in **IntercomWrapper.h**
```
#if __has_include(<React/RCTAssert.h>)
#import <React/RCTBridgeModule.h>
#import <React/RCTUtils.h>
#else // back compatibility for RN version < 0.40
#import "RCTBridgeModule.h" // file not found.
#import "RCTUtils.h"
#endif
```

I am using:
RN@0.50.3
react@16.1.1
react-native-intercom@9.0.0

Any suggestions? Any Idea?

**Comment by chukitow** [comment]
@ifero did you follow the instructions for IOS?

- Adding Intercom framework
- Creating run script

https://github.com/intercom/intercom-ios

**Comment by ifero** [comment]
@chukitow Yes I did

**Comment by afilp** [comment]
@chukitow I have the same problem... I cannot release due to this, any solution? Thanks for any help you can provide!

**Comment by chukitow** [comment]
@ifero @afilp the steps that I followed in order to set up the library on IOS.

1 - npm install react-native-intercom --save
2 - react-native link
3 - Add the following scripts to AppDelegate.m

```
#import "Intercom/intercom.h"

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Initialize Intercom
    [Intercom setApiKey:@"<#ios_sdk-...#>" forAppId:@"<#your-app-id#>"];
}

- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
     [Intercom setDeviceToken:deviceToken];
}
```

**At this point I was facing the same error** _Missing Intercom/Intercom.h_ then I noticed I need to do some extra steps.

4 - [Download Intercom for iOS ](https://github.com/intercom/intercom-ios/archive/master.zip)and extract the zip.

5 - Go to your Xcode project's "General" settings. Drag Intercom.framework to the "Embedded Binaries" section. Make sure "Copy items if needed" is selected and click Finish.

6 - Create a new "Run Script Phase" in your app’s target’s "Build Phases" and paste the following snippet in the script text field:

```
 bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Intercom.framework/strip-frameworks.sh"
```

7 - You'll need to make sure that you have a `NSPhotoLibraryUsageDescription` entry in your Info.plist.

Hope this works for  guys.

**Comment by ifero** [comment]
@chukitow as I said my project uses Cocoapods. 
Your solution works without the use of Cocoapods. I need to use Cocoapods so static linking Intercom library is not a good solution.

**Comment by aramkarapetian** [comment]
We had the same issue and took as two days to figure out that when dragging framework into embedded frameworks it automatically adds root folder to path, but since we had path without including ${inherit} it would not see the path added by XCode. Let me know if you did not get what I mean, it was difficult to figure out and difficult to describe. Hope this helps.

**Comment by hannigand** [comment]
@aramkarapetian are you able to elaborate please? I dragged Intercom.framework into the root of my project, what do I need to do know? I'm not experienced with XCode. Thank you.

My AppDelegate.m can see the `Intercom.h` file, just the RNIntercom project cannot.

**Comment by aramkarapetian** [comment]
You should also have RNIntercom.a in Library list.

**Comment by hannigand** [comment]
@aramkarapetian thanks for the quick response - I have that inside `Libraries > RNIntercom.xcodeproj > Products > libRNIntercom.a`. It's in a red colour. I've also added it under `Link Binary with Libraries` on my project.

**Comment by sbadalyan** [comment]
I have also problem with case sensitive make sure that you have included `#import "Intercom/Intercom.h"` with capitalize "Intercom.h"

**Comment by jasonwiener** [comment]
We had this problem as well.  Needed to add the folder path for the Intercom.framework to the FRAMEWORK_SEARCH_PATHS.

**Comment by AndresCardonaDev** [comment]
Hi, Having fun too 👍 
So, im like @hannigand ; i followed the manual installation of Intercom library into the project, followed the steps; changed Frameworks and Header search paths to point to this new folder, used relative and absolute paths to the framework folder, still is not able to find that import....

Someone found a solution for this?
