### ISSUE TITLE
Accepting app access token instead of API key

### ISSUE THREAD

**Issue by jsonpoindexter** [tinycreative/react-native-intercom#158]
Are there any plans to use an Intercom app token instead of an API key?

**Comment by jaseemabbas** [comment]
+1

**Comment by WojciechCendrzak** [comment]
I've got information from Intercom `you (or someone from your team) needs to replace your API Keys with "Access Tokens" before Mar 5 to continue using the Intercom REST API. Any API calls or integrations using your old API Keys will fail after this date.
`. Is any chance to use this library with Access Token instead of API Keys?

**Comment by voshawn** [comment]
I just pinged intercom. I don't think this affects us: 

![image](https://user-images.githubusercontent.com/10394260/36908972-d04cb728-1e0a-11e8-8c25-8f7163b32188.png)
