### ISSUE TITLE
Support setApiKey in JS level

### ISSUE THREAD

**Issue by ohtangza** [tinycreative/react-native-intercom#188]
It's a little hassle for devs to set up the APIKey in JS level.

Especially, when we are applying conditional API key based on development environment (prod, debug), there is no easy way to configure this.

**Comment by brunolemos** [comment]
I believe it's a lot less safe to put it on js

**Comment by bennyhobart** [comment]
why so @brunolemos?

**Comment by wktq** [comment]
this is the reason why i switched to zendesk.
https://github.com/synapsestudios/react-native-zendesk-support

**Comment by Uniphix** [comment]
> why so @brunolemos?

The reason for this is because the ApiKey of Intercom could be discovered if exposed in like an Expo Application.  If you know what you are doing you could get the application bundle which may have the key exposed if it was a JavaScript function.  So this is why I think @brunolemos is correct, it's safer initializing the key via iOS or Android back-end.  One thing that may and could happen is instead maybe provide a way to expose it in the Info.plist

**Comment by gustavopch** [comment]
AFAIK secrets in Android code can also be extracted: https://rammic.github.io/2015/07/28/hiding-secrets-in-android-apps
