### ISSUE TITLE
What is the plan for this lib?

### ISSUE THREAD

**Issue by vongohren** [tinycreative/react-native-intercom#288]
It is a great library and people are using it, but closing all issues means you have some kind of plan or just tired. But seeing that it is not being followed up as there is no response to any of the new issues coming in, is unfortunate.

It would be sad to see this lib go down the drain so I hope to see any plan for life of this library.

Can this be handed over to intercom?
Sold to intercom?
I don't know, something.

Disclaimer, I personally don't have the capacity to do it myself, so I understand the owners. But that is why I'm raising the last two questions.

**Comment by browniefed** [comment]
Please stop.
The issues you posted were either feature request you could add or weren't achievable and were issues with intercom. Go complain to them.

You are extremely hypocritical at the end here. So please stop complaining or go write the code to actually contribute to this library that you're so keen on using for free.

**Comment by vongohren** [comment]
Wow, you sure are inclusive in your behavior @browniefed!
Thanks for making sure that I definitively won't help you out.
This could have been solved with a simple nice message saying those things you said, instead you take it as criticism and bring on a negative tone. Inspiring behavior 🎉

**Comment by browniefed** [comment]
Ha don't even pretend like you were ever going to help or contribute. Any small bit of research would have led to you realizing you weren't the first to request the things you requested and that they weren't possible.

You've made these requests months ago so pretending like you were ever going to help instead of just complain is sad.

**Comment by browniefed** [comment]
Feel free to submit a pull request and I'll happily review it and merge it like many others have done.

Or feel free to keep complaining that I'm not using my free time to help you out with literally impossible requests.

**Comment by vongohren** [comment]
One sentence about you being swamped and need help, changes a lot. 
No communication and closing issues like they are not worth jack shit, make a negative effect. 

It's all about starting the discussion and communication. And yes, with my initial request I hope to solve this quickly. Maybe there is something wrong I'm doing, somebody working on it whatever. But no communication leaves no room for understanding and "awesome" responses from the lib owner makes it super encouraging to help out. 

It's human to human interaction 101, you are the owner, you know the best, you can set a steering path. But instead, you close and don't say anything. Leaves room for confusion and reply with negative comments when people show some kind of interest. I think that is sad

**Comment by browniefed** [comment]
No. I'm not the owner. I didn't write this. I only have merge access.

Here is a good example of a contribution

https://github.com/tinycreative/react-native-intercom/pull/265

**Comment by vongohren** [comment]
Well you are still an important contributer.
You cant expect all people to do like this guy out of the blue, people are
different, and if this is your only standard, you got to change your
mindset a bit. A lot of people can deliver this, but they might need a bit
more communication to get there.
When there is no communication of the need, the process or how the lib is
run, it can be difficult to jump in
But we are done here, thanks for an example and communication, hope it can
go better next time.

**Comment by asamiller** [comment]
I created this library a few years ago because I wanted to use Intercom in a project. I open sourced it so others could build off what I did. But I ended up not using it anymore and didn’t have time to work on it. @browniefed generously offered to help out. For a couple years he’s been helping for no reason other than to be helpful to the React Native community. 

I think the important thing to understand is that this is developers like you sharing their work. If you don’t have time to contribute, that’s fine, but don’t expect someone to do it for you. If this library didn’t exist, what would you do? You wouldn’t expect @browniefed to write it for you. You’d have to write it yourself or bug Intercom. Feel free to do either of those things. I've reached out to Intercom a couple times because they really should take over this project (or write their own React Native client) but they haven't responded. 

I think we all need to understand that a lot of open source is just people sharing their work and their time when they can. We should all be respectful of that.

**Comment by vongohren** [comment]
I'm very respective to the open source environment and appreciate the effort. I have been wanting to get more into the community the last couple of years but trying to force some libs in the companies iv been working at, to go open source. So there is no misalignment there.

What I don't respect is rude behavior and the thought that everybody know what you know and shall understand the way things are done. All open source libs are run differently, hence my questions. But thinking people know this and understand this, makes one take assumptions and cut edges, leaving people a bit confused.

All that was needed was the courtesy to answer issues with a simple message on the issues inviting the person to do it themselves. Even if we are on the internet, it is allowed to respect other people. I do believe if I had asked in a face to face scenario, the exact same questions, there would at least be an answer, and not in a rude and negative way.
