### ISSUE TITLE
Intercom Modal Screen Back/Close/Exit button callback?

### ISSUE THREAD

**Issue by larryranches** [tinycreative/react-native-intercom#83]
Is there a callback function when the Intercom Back/Exit/Close buttons is pressed?  This would be useful when triggering a function when a user exits out of intercom back into the app and you want an action/event to fire.

Would this be a feature request? Ideas?

**Comment by zachrnolan** [comment]
+1

**Comment by browniefed** [comment]
Probably a feature request. Happy to accept a PR

**Comment by nazarTrynko** [comment]
+1

**Comment by gordysc** [comment]
It looks like this might get addressed in #223 ?

**Comment by jayporta** [comment]
There's still no close button in v.12.5.0 (iOS only, Android has a close button as well as use of the back button)

![img_0747](https://user-images.githubusercontent.com/15250836/50236272-f822a880-0387-11e9-84bb-9494256f915c.jpeg)

**Comment by browniefed** [comment]
Does Intercom have a configuration for this? If so happy to accept a PR

**Comment by jayporta** [comment]
Hey @browniefed my reply was not directly related to this request, sorry. I'm searching Intercom's docs and started a chat with them to find out how to add a close button. react-native-intercom 10.2 had a working close button but 12.5 does not. However, I have to use 12.5 because we need the logout() function which was added in that version. If I can figure it out I'll submit a PR.

Edit: There is a close button but it seems to be invisible. I can tap the upper right corner and Intercom will close, just have to figure out how to change the color of the button now. That may be a setting on Intercom's site.

Edit 2: I had to replace the old framework with the new from Intercom's site. Common sense but I missed it.

**Comment by browniefed** [comment]
Great, do update this with anything you find.
I only manage PRs on this library, I only sort of use it at my current place.

I believe 10.2 was using the older SDK from Intercom and 12.5 is recommended to use the latest, so I'm not sure if they changed anything on their end.

Intercom really doesn't provide a ton of design control which is understandable but unfortunate.

**Comment by jayporta** [comment]
@browniefed I just edited my post. Sending this so you get the notification. I just had to go download the latest framework from Intercom and add it to my project.

**Comment by browniefed** [comment]
👍 Great glad you got it resolved.

**Comment by jayporta** [comment]
Thanks for responding so quickly.
